name: Docs build check
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs-check.yml'
      - docs/**
  pull_request:
    paths:
      - '.github/workflows/docs-check.yml'
      - docs/**
jobs:
  build:
    if: github.repository == 'AppAndFlow/react-native-safe-area-context'
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: docs
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install docs deps
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn install
      - name: Build docs
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build
