name: JavaScript tests

on: [push, pull_request]

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.13.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Install example app dependencies
        run: yarn install
        working-directory: example
      - name: Run tests
        run: yarn test
      - name: Typecheck example app
        run: yarn typecheck
        working-directory: example
